# -*- coding: utf-8 -*-
"""ATM stimulator machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bK3htXG1swCAzKbwMR_xPiFIT7pq6JhZ
"""

def deposit():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    money=int(input("Enter amount to be deposited: "))
    customer["Amount"] = customer["Amount"] + money
def withdrawal():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    money=int(input("Enter amount to be withdrawn: "))
    if customer["Amount"] < money:
      print("Not enough balance")
      return customer['Amount']
    else:
      customer["Amount"] = customer["Amount"] - money
      return customer["Amount"]
def amount():
  print(customer["Amount"])

def pin_change():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    npin = int(input("Enter new PIN: "))
    n2pin = int(input("Confirm PIN: "))
    if npin != n2pin:
      print("Not same")
    else:
      print("PIN changed succesfully")

customer = {"Card number" : 1234 , "PIN" : 789 , "Amount" : 4500 }
cnum = int(input("Enter Card number: "))
if cnum != customer["Card number"]:
  print("Invalid Card Number")
else:
  p = 1
  while p==1:
    service = int(input("Services :\n 1-DEPOSIT \n 2-WITHDRAWAL \n 3-PIN CHANGE \n 4-AMOUNT CHECK \n 5-EXIT \n Enter Service: "))
    if service == 1:
      deposit()
    elif service == 2:
      print("new amount :" ,withdrawal())
    elif service == 3:
      pin_change()
    elif service == 4:
      amount()
    elif service == 5:
      p=0
      print("THANKS FOR USING SERVICES...")
      break
    else:
      print("Invalid choice")
    inp = input("more services?(Y/N): ")
    if inp == 'N' or inp == 'n':
      p = 0

def wid():
    ENTER_AMOUNT=int(input("ENTER AMOUNT"))
    print("VALIDATING AMOUNT")
    if D["balance"]> ENTER_AMOUNT:
        print("SUFFICIENT BALANCE")
        print("AMOUNT DEBITED:",  ENTER_AMOUNT)
        print("WITHDRAWL SUCCESSFUL")
        print("AMOUNT LEFT:",D["balance"]- ENTER_AMOUNT)
        print(" CARD EJECTED")
    else:
        print("INSUFFICIENT BALANCE")
        print(" CARD EJECTED")
def dep():
    AMOUNT=int(input("ENTER AMOUNT TO BE DEPOSITED:"))
    print("CASH DETECTED")
    print("CASH DEPOSITED SUCCESSFULLY!!!")
    print("AMOUNT:",AMOUNT,"IS CREDITED TO YOUR ACCOUNT")
    print(" CARD EJECTED")
def inq():
    print("BALANCE IN YOUR ACCOUNT:",D["balance"])
    print(" CARD EJECTED")
D={"acc_no":45457532,"balance":50000,"pin-no":45663}
print("INSERT CARD")
CARD_NO=int(input("ENTER CARD NO."))
PIN_NO=int(input("ENTER PIN NO."))
print(" SERVICES:")
print("WITHDRAWL")
print("DEPOSIT")
print("BALANCE ENQUIRY")
print("_EXIT")
SERVICES=input("ENTER SERVICES")
if SERVICES=="WITHDRAWL":
    wid()

elif SERVICES=="DEPOSIT":
    dep()

elif SERVICES=="BALANCE INQUIRY":
    inq()
elif SERVICES=="EXIT":
    print("CARD EJECTED")
    print("THANK YOU!!")
else:
    print("INVALID CHOICE")
    print("EJECT CARD")

Options = ["Balance", "Withdraw", "Change PIN", "Exit"]

print("----Welcome To ATM Services----")
print("Please Insert Your Card")
print("Your Card is Inserted")

if input("Please Enter Your Pin: ") == "1234":
    print("Your Pin is Accepted")
    for I in Options:
        print(I)

    SERVICES = int(input("Please Select Your Option: "))
    if SERVICES == 1:
        print("Your Balance is: 12")
    elif SERVICES == 2:
        WITHDRAW = int(input("Please Enter The Amount You Want To Withdraw: "))
        print(f"You Have Withdrawn: {WITHDRAW}")
    elif SERVICES == 3:
        NEW_PIN = input("Please Enter Your New Pin: ")
        print(f"Your Pin Has Been Changed To: {NEW_PIN}")
    elif SERVICES == 4:
        print("Thank You For Using Our Services")
    else:
        print("Invalid Option Selected")
else:
    print("Invalid Pin")

def wid():
  amount = int(input("Enter Amount: "))


  if amount <= 0:
    print("Invalid Amount")

  elif amount > accounts[card]["balance"]:
    print("Insufficient Funds")
    print("Balance:", accounts[card]["balance"])

  else:
    atm_cash = 50000

  if amount > atm_cash:
    print("ATM Out of Cash")

  else:
    accounts[card]["balance"] -= amount
    print("Please Collect Your Cash")
    print("Updated Balance:", accounts[card]["balance"])
def dep():
  amount = int(input("Enter Deposit Amount: "))

  if amount <= 0:
    print("Invalid Amount")

  else:
    accounts[card]["balance"] += amount
    print("Deposit Successful")
    print("Updated Balance:", accounts[card]["balance"])
def bal():
  print("Current Balance:", accounts[card]["balance"])


accounts = {
    "1234567890": {"pin": "1234", "balance": 5000},
    "9876543210": {"pin": "4321", "balance": 10000}
}

card = input("Enter Card Number: ")

if card in accounts:
    pin = input("Enter PIN: ")

    if pin == accounts[card]["pin"]:

        while True:
            print("\n----- ATM MENU -----")
            print("1. Withdraw")
            print("2. Deposit")
            print("3. Balance Inquiry")
            print("4. Exit")

            choice = input("Enter your choice: ")
            if choice == "1":
                wid()
            elif choice == "2":
                dep()
            elif choice == "3":
                bal()
            elif choice == "4":
                print("Card Ejected")
                print("Thank You!")
                break

            else:
                print("Invalid Choice")

            receipt = input("Print Receipt? (y/n): ")
            if receipt.lower() == "y":
                print("----- RECEIPT -----")
                print("Balance:", accounts[card]["balance"])

            again = input("Another Transaction? (y/n): ")
            if again.lower() != "y":
                print("Card Ejected")
                print("Thank You!")
                break

    else:
        print("Incorrect PIN")
        print("Card Ejected")

else:
    print("Invalid Card Number")

