# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EplTunmxil8ZN-Ph0FUaveyTI-P5qc8t
"""

l=[1,2,3,4,45,5]
l1=[]
for i in l :
  l1.append(i**2)

l1

[i**2 for i in l]

[i for i in l if i%2==0]

l1= ["hii", "hello", "heyy", "suprbraht"]

[i.upper() for i in l1]

[i.lower() for i in l1]

d={"key1": 1, "key2":2, "key3":3, "key4":4}

{k:v**2 for k, v in d.items()}

d.items()

{k:v*2 for k, v in d.items()}

d

d.items()

d

{k : v for k, v in d.items( ) if v>1}

def test():
     pass

def test1() :
  print("hi my name is khushi")

def test2():
  print("hello!!")

test1()

test2()

def test1() :
  return "hi my name is khushi"

test1()+ " singh"

def test2() :
 return "hello!!"

test2()

def test3():
    return"sudh",23,345.56,[1,2,3,3]

test3()

a,b,c,d=test3()

a

b

type(test3)

type(a)

type(test1)

type(test3())

def add():
  a=5+6/7
  return a

add()

def test7():
  return (1, 2, 3, 'example')

test5()

test5(2, 5,8)

def test6 (a,b):
  return a+b

test6(3,4)

test6("hi", "bye")

def test11(*args):
  return args

type(test11())

test11(1,2,3)

def test11(*kwargs):
  return kwargs+(1,2,3,4)

type (test11())

test11(1,2,3,"sudh","kumar",[1,2,3,4,4])

def test12(*khushi):
  return khushi

test12(1,2,3,34,4)

def test13(*args,a):
  return args,a

test13(1,2,3,4, a=23)

def test14(c=1,d =5,a=23,b=1 ):
  return a,b,c,d

test14()

test14(3,4)

test14(2,5,a=2345)

def test15(**kwargs):
  return kwargs

type(test())

test15()

test15(a=[1,2,3,4],b="khushi",c=23.45)

def add(x, y):
  return x + y

def minus(x, y):
  return x - y

def multiply(x, y):
  return x * y

def divide(x, y):
  if y == 0:
    return "Error! Division by zero."
  return x / y

print("the sum of 2 and 4 is", add(2,4))
print("the minus of 4 and 2 is", minus(4,2))
print("the multiplication of 2 and 4 is", multiply(2,4))
print("the division of 4 and 2 is", divide(2,4))

def calc(a,b,p):
  if(p=="+"):
    print(a+b)
  elif (p=="-"):
    print(a-b)
  elif(p=="*"):
    print(a*b)
  elif(p=="/"):
    print(a/b)
  return "done"
a=int(input("enter num1"))
b=int(input("enter num2"))
p=(input("enter operation"))
calc(a,b,p)


ATM MACHINE----------------------------------------------------------------------------------------------

card_number = int(input("Enter card number: "))
card_pin = int(input("Enter card pin: "))

print("Choose services:")
print("1. Withdrawal")
print("2. Check balance")
print("3. Deposit cash")
print("4. Exit")
choice= (input("enter your choice(1-4): "))

def pick(selected_choice):
      if(selected_choice==1):
         print("Withdrawal")
         amt1= int(input("Enter current amount: "))
         amt2= int(input("Enter amount to be withdrawn: "))
         return amt1 - amt2
      elif(selected_choice==2):
          print("Check balance")
          print("your current balance is")
          return amt1
      elif(selected_choice==3):
         print("Deposit cash")
         amt1= int(input("Enter current amount: "))
         amt2= int(input("Enter amount to be deposited: "))
         return amt1 + amt2
      elif(selected_choice==4):
         print("Exit")